# Generated by Django 4.2 on 2023-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_cat', models.CharField(choices=[('trainer', 'trainer'), ('counsellor', 'counsellor'), ('backoffice', 'backoffice'), ('admin', 'admin')], max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
