# Generated by Django 4.2 on 2023-04-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remark',
            field=models.CharField(max_length=100),
        ),
    ]
