# Generated by Django 4.2 on 2023-04-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='remark',
            new_name='remarks',
        ),
    ]
