# Generated by Django 4.2 on 2023-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_remark_task_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remarks',
            field=models.TextField(),
        ),
    ]
