# Generated by Django 4.2.2 on 2023-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Customer', 'Customer')], max_length=100),
        ),
    ]
