# Generated by Django 4.2.2 on 2023-06-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='address',
        ),
    ]
