# Generated by Django 4.2 on 2023-05-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_master',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product_sub_cat',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_master'),
        ),
        migrations.DeleteModel(
            name='Product_mst',
        ),
    ]
