# Generated by Django 4.2 on 2023-05-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_sub_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sub_cat',
            name='image',
            field=models.ImageField(upload_to='product_image'),
        ),
    ]
