# Generated by Django 4.2 on 2023-05-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_sub_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_sub_cat',
            name='image',
        ),
    ]
